// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"budgeting_system/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobQueue creates a new instance of MockJobQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobQueue {
	mock := &MockJobQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobQueue is an autogenerated mock type for the JobQueue type
type MockJobQueue struct {
	mock.Mock
}

type MockJobQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobQueue) EXPECT() *MockJobQueue_Expecter {
	return &MockJobQueue_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) Enqueue(ctx context.Context, jobType string, payload any) error {
	ret := _mock.Called(ctx, jobType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, jobType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockJobQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - jobType string
//   - payload any
func (_e *MockJobQueue_Expecter) Enqueue(ctx any, jobType any, payload any) *MockJobQueue_Enqueue_Call {
	return &MockJobQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, jobType, payload)}
}

func (_c *MockJobQueue_Enqueue_Call) Run(run func(ctx context.Context, jobType string, payload any)) *MockJobQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobQueue_Enqueue_Call) Return(err error) *MockJobQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, jobType string, payload any) error) *MockJobQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockJobQueue_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockJobQueue_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobQueue_Expecter) Start(ctx any) *MockJobQueue_Start_Call {
	return &MockJobQueue_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockJobQueue_Start_Call) Run(run func(ctx context.Context)) *MockJobQueue_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobQueue_Start_Call) Return() *MockJobQueue_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobQueue_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockJobQueue_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) Stop() {
	_mock.Called()
	return
}

// MockJobQueue_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockJobQueue_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockJobQueue_Expecter) Stop() *MockJobQueue_Stop_Call {
	return &MockJobQueue_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockJobQueue_Stop_Call) Run(run func()) *MockJobQueue_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobQueue_Stop_Call) Return() *MockJobQueue_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobQueue_Stop_Call) RunAndReturn(run func()) *MockJobQueue_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockCategorySeeder creates a new instance of MockCategorySeeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategorySeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategorySeeder {
	mock := &MockCategorySeeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategorySeeder is an autogenerated mock type for the CategorySeeder type
type MockCategorySeeder struct {
	mock.Mock
}

type MockCategorySeeder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategorySeeder) EXPECT() *MockCategorySeeder_Expecter {
	return &MockCategorySeeder_Expecter{mock: &_m.Mock}
}

// SeedCategoriesForUser provides a mock function for the type MockCategorySeeder
func (_mock *MockCategorySeeder) SeedCategoriesForUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SeedCategoriesForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategorySeeder_SeedCategoriesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedCategoriesForUser'
type MockCategorySeeder_SeedCategoriesForUser_Call struct {
	*mock.Call
}

// SeedCategoriesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCategorySeeder_Expecter) SeedCategoriesForUser(ctx any, userID any) *MockCategorySeeder_SeedCategoriesForUser_Call {
	return &MockCategorySeeder_SeedCategoriesForUser_Call{Call: _e.mock.On("SeedCategoriesForUser", ctx, userID)}
}

func (_c *MockCategorySeeder_SeedCategoriesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockCategorySeeder_SeedCategoriesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategorySeeder_SeedCategoriesForUser_Call) Return(err error) *MockCategorySeeder_SeedCategoriesForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategorySeeder_SeedCategoriesForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockCategorySeeder_SeedCategoriesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetUserByBasiqUserID provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserByBasiqUserID(ctx context.Context, basiqUserID string) (*domain.User, error) {
	ret := _mock.Called(ctx, basiqUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByBasiqUserID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, basiqUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, basiqUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, basiqUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserByBasiqUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByBasiqUserID'
type MockAuthService_GetUserByBasiqUserID_Call struct {
	*mock.Call
}

// GetUserByBasiqUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - basiqUserID string
func (_e *MockAuthService_Expecter) GetUserByBasiqUserID(ctx any, basiqUserID any) *MockAuthService_GetUserByBasiqUserID_Call {
	return &MockAuthService_GetUserByBasiqUserID_Call{Call: _e.mock.On("GetUserByBasiqUserID", ctx, basiqUserID)}
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) Run(run func(ctx context.Context, basiqUserID string)) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) Return(user *domain.User, err error) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) RunAndReturn(run func(ctx context.Context, basiqUserID string) (*domain.User, error)) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) GetUserByID(ctx any, userID any) *MockAuthService_GetUserByID_Call {
	return &MockAuthService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockAuthService_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) Return(user *domain.User, err error) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.User, error)) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx any, email any, password any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(user *domain.User, err error) *MockAuthService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.User, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, email string, password string, firstName string, lastName string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password, firstName, lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - firstName string
//   - lastName string
func (_e *MockAuthService_Expecter) Register(ctx any, email any, password any, firstName any, lastName any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, firstName, lastName)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, password string, firstName string, lastName string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(user *domain.User, err error) *MockAuthService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string, firstName string, lastName string) (*domain.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBudgetService creates a new instance of MockBudgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBudgetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBudgetService {
	mock := &MockBudgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBudgetService is an autogenerated mock type for the BudgetService type
type MockBudgetService struct {
	mock.Mock
}

type MockBudgetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBudgetService) EXPECT() *MockBudgetService_Expecter {
	return &MockBudgetService_Expecter{mock: &_m.Mock}
}

// AddCategoryToBudget provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) AddCategoryToBudget(ctx context.Context, budgetID string, catID string) (*domain.BudgetCategory, error) {
	ret := _mock.Called(ctx, budgetID, catID)

	if len(ret) == 0 {
		panic("no return value specified for AddCategoryToBudget")
	}

	var r0 *domain.BudgetCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.BudgetCategory, error)); ok {
		return returnFunc(ctx, budgetID, catID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.BudgetCategory); ok {
		r0 = returnFunc(ctx, budgetID, catID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BudgetCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, budgetID, catID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_AddCategoryToBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCategoryToBudget'
type MockBudgetService_AddCategoryToBudget_Call struct {
	*mock.Call
}

// AddCategoryToBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - catID string
func (_e *MockBudgetService_Expecter) AddCategoryToBudget(ctx any, budgetID any, catID any) *MockBudgetService_AddCategoryToBudget_Call {
	return &MockBudgetService_AddCategoryToBudget_Call{Call: _e.mock.On("AddCategoryToBudget", ctx, budgetID, catID)}
}

func (_c *MockBudgetService_AddCategoryToBudget_Call) Run(run func(ctx context.Context, budgetID string, catID string)) *MockBudgetService_AddCategoryToBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBudgetService_AddCategoryToBudget_Call) Return(budgetCategory *domain.BudgetCategory, err error) *MockBudgetService_AddCategoryToBudget_Call {
	_c.Call.Return(budgetCategory, err)
	return _c
}

func (_c *MockBudgetService_AddCategoryToBudget_Call) RunAndReturn(run func(ctx context.Context, budgetID string, catID string) (*domain.BudgetCategory, error)) *MockBudgetService_AddCategoryToBudget_Call {
	_c.Call.Return(run)
	return _c
}

// AssignCategoryFunds provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) AssignCategoryFunds(ctx context.Context, budgetID string, catID string, amount int64, frequency domain.BudgetFrequency, replace bool) (*domain.BudgetCategory, error) {
	ret := _mock.Called(ctx, budgetID, catID, amount, frequency, replace)

	if len(ret) == 0 {
		panic("no return value specified for AssignCategoryFunds")
	}

	var r0 *domain.BudgetCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, domain.BudgetFrequency, bool) (*domain.BudgetCategory, error)); ok {
		return returnFunc(ctx, budgetID, catID, amount, frequency, replace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, domain.BudgetFrequency, bool) *domain.BudgetCategory); ok {
		r0 = returnFunc(ctx, budgetID, catID, amount, frequency, replace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BudgetCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, domain.BudgetFrequency, bool) error); ok {
		r1 = returnFunc(ctx, budgetID, catID, amount, frequency, replace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_AssignCategoryFunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignCategoryFunds'
type MockBudgetService_AssignCategoryFunds_Call struct {
	*mock.Call
}

// AssignCategoryFunds is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - catID string
//   - amount int64
//   - frequency domain.BudgetFrequency
//   - replace bool
func (_e *MockBudgetService_Expecter) AssignCategoryFunds(ctx any, budgetID any, catID any, amount any, frequency any, replace any) *MockBudgetService_AssignCategoryFunds_Call {
	return &MockBudgetService_AssignCategoryFunds_Call{Call: _e.mock.On("AssignCategoryFunds", ctx, budgetID, catID, amount, frequency, replace)}
}

func (_c *MockBudgetService_AssignCategoryFunds_Call) Run(run func(ctx context.Context, budgetID string, catID string, amount int64, frequency domain.BudgetFrequency, replace bool)) *MockBudgetService_AssignCategoryFunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 domain.BudgetFrequency
		if args[4] != nil {
			arg4 = args[4].(domain.BudgetFrequency)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBudgetService_AssignCategoryFunds_Call) Return(budgetCategory *domain.BudgetCategory, err error) *MockBudgetService_AssignCategoryFunds_Call {
	_c.Call.Return(budgetCategory, err)
	return _c
}

func (_c *MockBudgetService_AssignCategoryFunds_Call) RunAndReturn(run func(ctx context.Context, budgetID string, catID string, amount int64, frequency domain.BudgetFrequency, replace bool) (*domain.BudgetCategory, error)) *MockBudgetService_AssignCategoryFunds_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Create(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, userID, name, method, currency, period, startDate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, userID, name, method, currency, period, startDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, userID, name, method, currency, period, startDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) error); ok {
		r1 = returnFunc(ctx, userID, name, method, currency, period, startDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBudgetService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - method domain.BudgetMethod
//   - currency string
//   - period domain.BudgetPeriod
//   - startDate string
func (_e *MockBudgetService_Expecter) Create(ctx any, userID any, name any, method any, currency any, period any, startDate any) *MockBudgetService_Create_Call {
	return &MockBudgetService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, method, currency, period, startDate)}
}

func (_c *MockBudgetService_Create_Call) Run(run func(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string)) *MockBudgetService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.BudgetMethod
		if args[3] != nil {
			arg3 = args[3].(domain.BudgetMethod)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 domain.BudgetPeriod
		if args[5] != nil {
			arg5 = args[5].(domain.BudgetPeriod)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockBudgetService_Create_Call) Return(budget *domain.Budget, err error) *MockBudgetService_Create_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string) (*domain.Budget, error)) *MockBudgetService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBudgetService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBudgetService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) Delete(ctx any, id any) *MockBudgetService_Delete_Call {
	return &MockBudgetService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBudgetService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_Delete_Call) Return(err error) *MockBudgetService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBudgetService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockBudgetService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FundEnvelope provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) FundEnvelope(ctx context.Context, budgetID string, catID string, accountID string, amount int64) (*domain.Account, *domain.BudgetCategory, error) {
	ret := _mock.Called(ctx, budgetID, catID, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for FundEnvelope")
	}

	var r0 *domain.Account
	var r1 *domain.BudgetCategory
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (*domain.Account, *domain.BudgetCategory, error)); ok {
		return returnFunc(ctx, budgetID, catID, accountID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) *domain.Account); ok {
		r0 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64) *domain.BudgetCategory); ok {
		r1 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.BudgetCategory)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, int64) error); ok {
		r2 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBudgetService_FundEnvelope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundEnvelope'
type MockBudgetService_FundEnvelope_Call struct {
	*mock.Call
}

// FundEnvelope is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - catID string
//   - accountID string
//   - amount int64
func (_e *MockBudgetService_Expecter) FundEnvelope(ctx any, budgetID any, catID any, accountID any, amount any) *MockBudgetService_FundEnvelope_Call {
	return &MockBudgetService_FundEnvelope_Call{Call: _e.mock.On("FundEnvelope", ctx, budgetID, catID, accountID, amount)}
}

func (_c *MockBudgetService_FundEnvelope_Call) Run(run func(ctx context.Context, budgetID string, catID string, accountID string, amount int64)) *MockBudgetService_FundEnvelope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBudgetService_FundEnvelope_Call) Return(account *domain.Account, budgetCategory *domain.BudgetCategory, err error) *MockBudgetService_FundEnvelope_Call {
	_c.Call.Return(account, budgetCategory, err)
	return _c
}

func (_c *MockBudgetService_FundEnvelope_Call) RunAndReturn(run func(ctx context.Context, budgetID string, catID string, accountID string, amount int64) (*domain.Account, *domain.BudgetCategory, error)) *MockBudgetService_FundEnvelope_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) GetByID(ctx context.Context, id string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBudgetService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) GetByID(ctx any, id any) *MockBudgetService_GetByID_Call {
	return &MockBudgetService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBudgetService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_GetByID_Call) Return(budget *domain.Budget, err error) *MockBudgetService_GetByID_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Budget, error)) *MockBudgetService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) GetSummary(ctx context.Context, id string) (any, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type MockBudgetService_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) GetSummary(ctx any, id any) *MockBudgetService_GetSummary_Call {
	return &MockBudgetService_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, id)}
}

func (_c *MockBudgetService_GetSummary_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_GetSummary_Call) Return(v any, err error) *MockBudgetService_GetSummary_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBudgetService_GetSummary_Call) RunAndReturn(run func(ctx context.Context, id string) (any, error)) *MockBudgetService_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) List(ctx context.Context, userID string) ([]*domain.Budget, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Budget, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Budget); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBudgetService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBudgetService_Expecter) List(ctx any, userID any) *MockBudgetService_List_Call {
	return &MockBudgetService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockBudgetService_List_Call) Run(run func(ctx context.Context, userID string)) *MockBudgetService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_List_Call) Return(budgets []*domain.Budget, err error) *MockBudgetService_List_Call {
	_c.Call.Return(budgets, err)
	return _c
}

func (_c *MockBudgetService_List_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Budget, error)) *MockBudgetService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailableCategories provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) ListAvailableCategories(ctx context.Context, budgetID string) ([]*domain.Category, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableCategories")
	}

	var r0 []*domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Category, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Category); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_ListAvailableCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailableCategories'
type MockBudgetService_ListAvailableCategories_Call struct {
	*mock.Call
}

// ListAvailableCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockBudgetService_Expecter) ListAvailableCategories(ctx any, budgetID any) *MockBudgetService_ListAvailableCategories_Call {
	return &MockBudgetService_ListAvailableCategories_Call{Call: _e.mock.On("ListAvailableCategories", ctx, budgetID)}
}

func (_c *MockBudgetService_ListAvailableCategories_Call) Run(run func(ctx context.Context, budgetID string)) *MockBudgetService_ListAvailableCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_ListAvailableCategories_Call) Return(categorys []*domain.Category, err error) *MockBudgetService_ListAvailableCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockBudgetService_ListAvailableCategories_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Category, error)) *MockBudgetService_ListAvailableCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListBudgetCategories provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) ListBudgetCategories(ctx context.Context, budgetID string) ([]*domain.BudgetCategory, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ListBudgetCategories")
	}

	var r0 []*domain.BudgetCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.BudgetCategory, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.BudgetCategory); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BudgetCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_ListBudgetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBudgetCategories'
type MockBudgetService_ListBudgetCategories_Call struct {
	*mock.Call
}

// ListBudgetCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockBudgetService_Expecter) ListBudgetCategories(ctx any, budgetID any) *MockBudgetService_ListBudgetCategories_Call {
	return &MockBudgetService_ListBudgetCategories_Call{Call: _e.mock.On("ListBudgetCategories", ctx, budgetID)}
}

func (_c *MockBudgetService_ListBudgetCategories_Call) Run(run func(ctx context.Context, budgetID string)) *MockBudgetService_ListBudgetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_ListBudgetCategories_Call) Return(budgetCategorys []*domain.BudgetCategory, err error) *MockBudgetService_ListBudgetCategories_Call {
	_c.Call.Return(budgetCategorys, err)
	return _c
}

func (_c *MockBudgetService_ListBudgetCategories_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.BudgetCategory, error)) *MockBudgetService_ListBudgetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileAllForUser provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) ReconcileAllForUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBudgetService_ReconcileAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileAllForUser'
type MockBudgetService_ReconcileAllForUser_Call struct {
	*mock.Call
}

// ReconcileAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBudgetService_Expecter) ReconcileAllForUser(ctx any, userID any) *MockBudgetService_ReconcileAllForUser_Call {
	return &MockBudgetService_ReconcileAllForUser_Call{Call: _e.mock.On("ReconcileAllForUser", ctx, userID)}
}

func (_c *MockBudgetService_ReconcileAllForUser_Call) Run(run func(ctx context.Context, userID string)) *MockBudgetService_ReconcileAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_ReconcileAllForUser_Call) Return(err error) *MockBudgetService_ReconcileAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBudgetService_ReconcileAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockBudgetService_ReconcileAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileForAccount provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) ReconcileForAccount(ctx context.Context, accountID string) error {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileForAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBudgetService_ReconcileForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileForAccount'
type MockBudgetService_ReconcileForAccount_Call struct {
	*mock.Call
}

// ReconcileForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockBudgetService_Expecter) ReconcileForAccount(ctx any, accountID any) *MockBudgetService_ReconcileForAccount_Call {
	return &MockBudgetService_ReconcileForAccount_Call{Call: _e.mock.On("ReconcileForAccount", ctx, accountID)}
}

func (_c *MockBudgetService_ReconcileForAccount_Call) Run(run func(ctx context.Context, accountID string)) *MockBudgetService_ReconcileForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_ReconcileForAccount_Call) Return(err error) *MockBudgetService_ReconcileForAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBudgetService_ReconcileForAccount_Call) RunAndReturn(run func(ctx context.Context, accountID string) error) *MockBudgetService_ReconcileForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileFromTransactions provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) ReconcileFromTransactions(ctx context.Context, budgetID string) error {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileFromTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBudgetService_ReconcileFromTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileFromTransactions'
type MockBudgetService_ReconcileFromTransactions_Call struct {
	*mock.Call
}

// ReconcileFromTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockBudgetService_Expecter) ReconcileFromTransactions(ctx any, budgetID any) *MockBudgetService_ReconcileFromTransactions_Call {
	return &MockBudgetService_ReconcileFromTransactions_Call{Call: _e.mock.On("ReconcileFromTransactions", ctx, budgetID)}
}

func (_c *MockBudgetService_ReconcileFromTransactions_Call) Run(run func(ctx context.Context, budgetID string)) *MockBudgetService_ReconcileFromTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_ReconcileFromTransactions_Call) Return(err error) *MockBudgetService_ReconcileFromTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBudgetService_ReconcileFromTransactions_Call) RunAndReturn(run func(ctx context.Context, budgetID string) error) *MockBudgetService_ReconcileFromTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Update(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, id, name, method, currency, period, startDate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, id, name, method, currency, period, startDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, id, name, method, currency, period, startDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.BudgetMethod, string, domain.BudgetPeriod, string) error); ok {
		r1 = returnFunc(ctx, id, name, method, currency, period, startDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBudgetService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - method domain.BudgetMethod
//   - currency string
//   - period domain.BudgetPeriod
//   - startDate string
func (_e *MockBudgetService_Expecter) Update(ctx any, id any, name any, method any, currency any, period any, startDate any) *MockBudgetService_Update_Call {
	return &MockBudgetService_Update_Call{Call: _e.mock.On("Update", ctx, id, name, method, currency, period, startDate)}
}

func (_c *MockBudgetService_Update_Call) Run(run func(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string)) *MockBudgetService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.BudgetMethod
		if args[3] != nil {
			arg3 = args[3].(domain.BudgetMethod)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 domain.BudgetPeriod
		if args[5] != nil {
			arg5 = args[5].(domain.BudgetPeriod)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockBudgetService_Update_Call) Return(budget *domain.Budget, err error) *MockBudgetService_Update_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string, period domain.BudgetPeriod, startDate string) (*domain.Budget, error)) *MockBudgetService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Create(ctx context.Context, userID string, name string, accType domain.AccountType, balance int64) (*domain.Account, error) {
	ret := _mock.Called(ctx, userID, name, accType, balance)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.AccountType, int64) (*domain.Account, error)); ok {
		return returnFunc(ctx, userID, name, accType, balance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.AccountType, int64) *domain.Account); ok {
		r0 = returnFunc(ctx, userID, name, accType, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.AccountType, int64) error); ok {
		r1 = returnFunc(ctx, userID, name, accType, balance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - accType domain.AccountType
//   - balance int64
func (_e *MockAccountService_Expecter) Create(ctx any, userID any, name any, accType any, balance any) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, accType, balance)}
}

func (_c *MockAccountService_Create_Call) Run(run func(ctx context.Context, userID string, name string, accType domain.AccountType, balance int64)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.AccountType
		if args[3] != nil {
			arg3 = args[3].(domain.AccountType)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(account *domain.Account, err error) *MockAccountService_Create_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, name string, accType domain.AccountType, balance int64) (*domain.Account, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountService_Expecter) Delete(ctx any, id any) *MockAccountService_Delete_Call {
	return &MockAccountService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAccountService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_Delete_Call) Return(err error) *MockAccountService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAccountService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetByID(ctx context.Context, id string) (*domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountService_Expecter) GetByID(ctx any, id any) *MockAccountService_GetByID_Call {
	return &MockAccountService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockAccountService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_GetByID_Call) Return(account *domain.Account, err error) *MockAccountService_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Account, error)) *MockAccountService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// LinkToBudget provides a mock function for the type MockAccountService
func (_mock *MockAccountService) LinkToBudget(ctx context.Context, budgetID string, accountID string, userID string) error {
	ret := _mock.Called(ctx, budgetID, accountID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LinkToBudget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, budgetID, accountID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountService_LinkToBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkToBudget'
type MockAccountService_LinkToBudget_Call struct {
	*mock.Call
}

// LinkToBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - accountID string
//   - userID string
func (_e *MockAccountService_Expecter) LinkToBudget(ctx any, budgetID any, accountID any, userID any) *MockAccountService_LinkToBudget_Call {
	return &MockAccountService_LinkToBudget_Call{Call: _e.mock.On("LinkToBudget", ctx, budgetID, accountID, userID)}
}

func (_c *MockAccountService_LinkToBudget_Call) Run(run func(ctx context.Context, budgetID string, accountID string, userID string)) *MockAccountService_LinkToBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountService_LinkToBudget_Call) Return(err error) *MockAccountService_LinkToBudget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountService_LinkToBudget_Call) RunAndReturn(run func(ctx context.Context, budgetID string, accountID string, userID string) error) *MockAccountService_LinkToBudget_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAccountService
func (_mock *MockAccountService) List(ctx context.Context, userID string) ([]*domain.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAccountService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountService_Expecter) List(ctx any, userID any) *MockAccountService_List_Call {
	return &MockAccountService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockAccountService_List_Call) Run(run func(ctx context.Context, userID string)) *MockAccountService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_List_Call) Return(accounts []*domain.Account, err error) *MockAccountService_List_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountService_List_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Account, error)) *MockAccountService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByBudget provides a mock function for the type MockAccountService
func (_mock *MockAccountService) ListByBudget(ctx context.Context, budgetID string) ([]*domain.Account, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ListByBudget")
	}

	var r0 []*domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Account, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Account); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_ListByBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByBudget'
type MockAccountService_ListByBudget_Call struct {
	*mock.Call
}

// ListByBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockAccountService_Expecter) ListByBudget(ctx any, budgetID any) *MockAccountService_ListByBudget_Call {
	return &MockAccountService_ListByBudget_Call{Call: _e.mock.On("ListByBudget", ctx, budgetID)}
}

func (_c *MockAccountService_ListByBudget_Call) Run(run func(ctx context.Context, budgetID string)) *MockAccountService_ListByBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_ListByBudget_Call) Return(accounts []*domain.Account, err error) *MockAccountService_ListByBudget_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountService_ListByBudget_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Account, error)) *MockAccountService_ListByBudget_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkFromBudget provides a mock function for the type MockAccountService
func (_mock *MockAccountService) UnlinkFromBudget(ctx context.Context, budgetID string, accountID string, userID string) error {
	ret := _mock.Called(ctx, budgetID, accountID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkFromBudget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, budgetID, accountID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountService_UnlinkFromBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkFromBudget'
type MockAccountService_UnlinkFromBudget_Call struct {
	*mock.Call
}

// UnlinkFromBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - accountID string
//   - userID string
func (_e *MockAccountService_Expecter) UnlinkFromBudget(ctx any, budgetID any, accountID any, userID any) *MockAccountService_UnlinkFromBudget_Call {
	return &MockAccountService_UnlinkFromBudget_Call{Call: _e.mock.On("UnlinkFromBudget", ctx, budgetID, accountID, userID)}
}

func (_c *MockAccountService_UnlinkFromBudget_Call) Run(run func(ctx context.Context, budgetID string, accountID string, userID string)) *MockAccountService_UnlinkFromBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountService_UnlinkFromBudget_Call) Return(err error) *MockAccountService_UnlinkFromBudget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountService_UnlinkFromBudget_Call) RunAndReturn(run func(ctx context.Context, budgetID string, accountID string, userID string) error) *MockAccountService_UnlinkFromBudget_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Update(ctx context.Context, acc *domain.Account) (*domain.Account, error) {
	ret := _mock.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Account) (*domain.Account, error)); ok {
		return returnFunc(ctx, acc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Account) *domain.Account); ok {
		r0 = returnFunc(ctx, acc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Account) error); ok {
		r1 = returnFunc(ctx, acc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *domain.Account
func (_e *MockAccountService_Expecter) Update(ctx any, acc any) *MockAccountService_Update_Call {
	return &MockAccountService_Update_Call{Call: _e.mock.On("Update", ctx, acc)}
}

func (_c *MockAccountService_Update_Call) Run(run func(ctx context.Context, acc *domain.Account)) *MockAccountService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Account
		if args[1] != nil {
			arg1 = args[1].(*domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_Update_Call) Return(account *domain.Account, err error) *MockAccountService_Update_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_Update_Call) RunAndReturn(run func(ctx context.Context, acc *domain.Account) (*domain.Account, error)) *MockAccountService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Create(ctx context.Context, userID string, cat *domain.Category) (*domain.Category, error) {
	ret := _mock.Called(ctx, userID, cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Category) (*domain.Category, error)); ok {
		return returnFunc(ctx, userID, cat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Category) *domain.Category); ok {
		r0 = returnFunc(ctx, userID, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.Category) error); ok {
		r1 = returnFunc(ctx, userID, cat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - cat *domain.Category
func (_e *MockCategoryService_Expecter) Create(ctx any, userID any, cat any) *MockCategoryService_Create_Call {
	return &MockCategoryService_Create_Call{Call: _e.mock.On("Create", ctx, userID, cat)}
}

func (_c *MockCategoryService_Create_Call) Run(run func(ctx context.Context, userID string, cat *domain.Category)) *MockCategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.Category
		if args[2] != nil {
			arg2 = args[2].(*domain.Category)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategoryService_Create_Call) Return(category *domain.Category, err error) *MockCategoryService_Create_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, cat *domain.Category) (*domain.Category, error)) *MockCategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCategoryService_Expecter) Delete(ctx any, id any) *MockCategoryService_Delete_Call {
	return &MockCategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_Delete_Call) Return(err error) *MockCategoryService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockCategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) GetByID(ctx context.Context, id string) (*domain.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCategoryService_Expecter) GetByID(ctx any, id any) *MockCategoryService_GetByID_Call {
	return &MockCategoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCategoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_GetByID_Call) Return(category *domain.Category, err error) *MockCategoryService_GetByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Category, error)) *MockCategoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) List(ctx context.Context, userID string) ([]*domain.Category, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Category, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Category); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCategoryService_Expecter) List(ctx any, userID any) *MockCategoryService_List_Call {
	return &MockCategoryService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockCategoryService_List_Call) Run(run func(ctx context.Context, userID string)) *MockCategoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_List_Call) Return(categorys []*domain.Category, err error) *MockCategoryService_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryService_List_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Category, error)) *MockCategoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Update(ctx context.Context, cat *domain.Category) (*domain.Category, error) {
	ret := _mock.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Category) (*domain.Category, error)); ok {
		return returnFunc(ctx, cat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Category) *domain.Category); ok {
		r0 = returnFunc(ctx, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Category) error); ok {
		r1 = returnFunc(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cat *domain.Category
func (_e *MockCategoryService_Expecter) Update(ctx any, cat any) *MockCategoryService_Update_Call {
	return &MockCategoryService_Update_Call{Call: _e.mock.On("Update", ctx, cat)}
}

func (_c *MockCategoryService_Update_Call) Run(run func(ctx context.Context, cat *domain.Category)) *MockCategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Category
		if args[1] != nil {
			arg1 = args[1].(*domain.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_Update_Call) Return(category *domain.Category, err error) *MockCategoryService_Update_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Update_Call) RunAndReturn(run func(ctx context.Context, cat *domain.Category) (*domain.Category, error)) *MockCategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Create(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID, accountID, categoryID, amount, description, date)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, time.Time) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, time.Time) *domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, string, time.Time) error); ok {
		r1 = returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - accountID string
//   - categoryID string
//   - amount int64
//   - description string
//   - date time.Time
func (_e *MockTransactionService_Expecter) Create(ctx any, budgetID any, accountID any, categoryID any, amount any, description any, date any) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, budgetID, accountID, categoryID, amount, description, date)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(transaction *domain.Transaction, err error) *MockTransactionService_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time) (*domain.Transaction, error)) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Delete(ctx context.Context, budgetID string, txID string) error {
	ret := _mock.Called(ctx, budgetID, txID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, budgetID, txID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - txID string
func (_e *MockTransactionService_Expecter) Delete(ctx any, budgetID any, txID any) *MockTransactionService_Delete_Call {
	return &MockTransactionService_Delete_Call{Call: _e.mock.On("Delete", ctx, budgetID, txID)}
}

func (_c *MockTransactionService_Delete_Call) Run(run func(ctx context.Context, budgetID string, txID string)) *MockTransactionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionService_Delete_Call) Return(err error) *MockTransactionService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionService_Delete_Call) RunAndReturn(run func(ctx context.Context, budgetID string, txID string) error) *MockTransactionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) List(ctx context.Context, budgetID string) ([]*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockTransactionService_Expecter) List(ctx any, budgetID any) *MockTransactionService_List_Call {
	return &MockTransactionService_List_Call{Call: _e.mock.On("List", ctx, budgetID)}
}

func (_c *MockTransactionService_List_Call) Run(run func(ctx context.Context, budgetID string)) *MockTransactionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionService_List_Call) Return(transactions []*domain.Transaction, err error) *MockTransactionService_List_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionService_List_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Transaction, error)) *MockTransactionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) ListByUser(ctx context.Context, userID string) ([]*domain.Transaction, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Transaction, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Transaction); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTransactionService_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTransactionService_Expecter) ListByUser(ctx any, userID any) *MockTransactionService_ListByUser_Call {
	return &MockTransactionService_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTransactionService_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTransactionService_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionService_ListByUser_Call) Return(transactions []*domain.Transaction, err error) *MockTransactionService_ListByUser_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionService_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Transaction, error)) *MockTransactionService_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Update(ctx context.Context, budgetID string, txID string, updates *domain.Transaction, customerCategory *string) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID, txID, updates, customerCategory)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Transaction, *string) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID, txID, updates, customerCategory)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Transaction, *string) *domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID, txID, updates, customerCategory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.Transaction, *string) error); ok {
		r1 = returnFunc(ctx, budgetID, txID, updates, customerCategory)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - txID string
//   - updates *domain.Transaction
//   - customerCategory *string
func (_e *MockTransactionService_Expecter) Update(ctx any, budgetID any, txID any, updates any, customerCategory any) *MockTransactionService_Update_Call {
	return &MockTransactionService_Update_Call{Call: _e.mock.On("Update", ctx, budgetID, txID, updates, customerCategory)}
}

func (_c *MockTransactionService_Update_Call) Run(run func(ctx context.Context, budgetID string, txID string, updates *domain.Transaction, customerCategory *string)) *MockTransactionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.Transaction
		if args[3] != nil {
			arg3 = args[3].(*domain.Transaction)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTransactionService_Update_Call) Return(transaction *domain.Transaction, err error) *MockTransactionService_Update_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionService_Update_Call) RunAndReturn(run func(ctx context.Context, budgetID string, txID string, updates *domain.Transaction, customerCategory *string) (*domain.Transaction, error)) *MockTransactionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBankSyncService creates a new instance of MockBankSyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankSyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankSyncService {
	mock := &MockBankSyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankSyncService is an autogenerated mock type for the BankSyncService type
type MockBankSyncService struct {
	mock.Mock
}

type MockBankSyncService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankSyncService) EXPECT() *MockBankSyncService_Expecter {
	return &MockBankSyncService_Expecter{mock: &_m.Mock}
}

// GetAuthLink provides a mock function for the type MockBankSyncService
func (_mock *MockBankSyncService) GetAuthLink(ctx context.Context, userID string) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthLink")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBankSyncService_GetAuthLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthLink'
type MockBankSyncService_GetAuthLink_Call struct {
	*mock.Call
}

// GetAuthLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBankSyncService_Expecter) GetAuthLink(ctx any, userID any) *MockBankSyncService_GetAuthLink_Call {
	return &MockBankSyncService_GetAuthLink_Call{Call: _e.mock.On("GetAuthLink", ctx, userID)}
}

func (_c *MockBankSyncService_GetAuthLink_Call) Run(run func(ctx context.Context, userID string)) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankSyncService_GetAuthLink_Call) Return(s string, s1 string, err error) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockBankSyncService_GetAuthLink_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, string, error)) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Return(run)
	return _c
}

// SyncUser provides a mock function for the type MockBankSyncService
func (_mock *MockBankSyncService) SyncUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SyncUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankSyncService_SyncUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncUser'
type MockBankSyncService_SyncUser_Call struct {
	*mock.Call
}

// SyncUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBankSyncService_Expecter) SyncUser(ctx any, userID any) *MockBankSyncService_SyncUser_Call {
	return &MockBankSyncService_SyncUser_Call{Call: _e.mock.On("SyncUser", ctx, userID)}
}

func (_c *MockBankSyncService_SyncUser_Call) Run(run func(ctx context.Context, userID string)) *MockBankSyncService_SyncUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankSyncService_SyncUser_Call) Return(err error) *MockBankSyncService_SyncUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankSyncService_SyncUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockBankSyncService_SyncUser_Call {
	_c.Call.Return(run)
	return _c
}
