// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"budgeting_system/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetUserByBasiqUserID provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserByBasiqUserID(ctx context.Context, basiqUserID string) (*domain.User, error) {
	ret := _mock.Called(ctx, basiqUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByBasiqUserID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, basiqUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, basiqUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, basiqUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserByBasiqUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByBasiqUserID'
type MockAuthService_GetUserByBasiqUserID_Call struct {
	*mock.Call
}

// GetUserByBasiqUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - basiqUserID string
func (_e *MockAuthService_Expecter) GetUserByBasiqUserID(ctx any, basiqUserID any) *MockAuthService_GetUserByBasiqUserID_Call {
	return &MockAuthService_GetUserByBasiqUserID_Call{Call: _e.mock.On("GetUserByBasiqUserID", ctx, basiqUserID)}
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) Run(run func(ctx context.Context, basiqUserID string)) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) Return(user *domain.User, err error) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_GetUserByBasiqUserID_Call) RunAndReturn(run func(ctx context.Context, basiqUserID string) (*domain.User, error)) *MockAuthService_GetUserByBasiqUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) GetUserByID(ctx any, userID any) *MockAuthService_GetUserByID_Call {
	return &MockAuthService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockAuthService_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) Return(user *domain.User, err error) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.User, error)) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx any, email any, password any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(user *domain.User, err error) *MockAuthService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.User, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, email string, password string, firstName string, lastName string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password, firstName, lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - firstName string
//   - lastName string
func (_e *MockAuthService_Expecter) Register(ctx any, email any, password any, firstName any, lastName any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, firstName, lastName)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, password string, firstName string, lastName string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(user *domain.User, err error) *MockAuthService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string, firstName string, lastName string) (*domain.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBudgetService creates a new instance of MockBudgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBudgetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBudgetService {
	mock := &MockBudgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBudgetService is an autogenerated mock type for the BudgetService type
type MockBudgetService struct {
	mock.Mock
}

type MockBudgetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBudgetService) EXPECT() *MockBudgetService_Expecter {
	return &MockBudgetService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Create(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, userID, name, method, currency)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, userID, name, method, currency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, userID, name, method, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.BudgetMethod, string) error); ok {
		r1 = returnFunc(ctx, userID, name, method, currency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBudgetService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - method domain.BudgetMethod
//   - currency string
func (_e *MockBudgetService_Expecter) Create(ctx any, userID any, name any, method any, currency any) *MockBudgetService_Create_Call {
	return &MockBudgetService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, method, currency)}
}

func (_c *MockBudgetService_Create_Call) Run(run func(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string)) *MockBudgetService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.BudgetMethod
		if args[3] != nil {
			arg3 = args[3].(domain.BudgetMethod)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBudgetService_Create_Call) Return(budget *domain.Budget, err error) *MockBudgetService_Create_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, name string, method domain.BudgetMethod, currency string) (*domain.Budget, error)) *MockBudgetService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBudgetService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBudgetService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) Delete(ctx any, id any) *MockBudgetService_Delete_Call {
	return &MockBudgetService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBudgetService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_Delete_Call) Return(err error) *MockBudgetService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBudgetService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockBudgetService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) GetByID(ctx context.Context, id string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBudgetService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) GetByID(ctx any, id any) *MockBudgetService_GetByID_Call {
	return &MockBudgetService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBudgetService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_GetByID_Call) Return(budget *domain.Budget, err error) *MockBudgetService_GetByID_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Budget, error)) *MockBudgetService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) GetSummary(ctx context.Context, id string) (any, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type MockBudgetService_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBudgetService_Expecter) GetSummary(ctx any, id any) *MockBudgetService_GetSummary_Call {
	return &MockBudgetService_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, id)}
}

func (_c *MockBudgetService_GetSummary_Call) Run(run func(ctx context.Context, id string)) *MockBudgetService_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_GetSummary_Call) Return(v any, err error) *MockBudgetService_GetSummary_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBudgetService_GetSummary_Call) RunAndReturn(run func(ctx context.Context, id string) (any, error)) *MockBudgetService_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) List(ctx context.Context, userID string) ([]*domain.Budget, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Budget, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Budget); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBudgetService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBudgetService_Expecter) List(ctx any, userID any) *MockBudgetService_List_Call {
	return &MockBudgetService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockBudgetService_List_Call) Run(run func(ctx context.Context, userID string)) *MockBudgetService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBudgetService_List_Call) Return(budgets []*domain.Budget, err error) *MockBudgetService_List_Call {
	_c.Call.Return(budgets, err)
	return _c
}

func (_c *MockBudgetService_List_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Budget, error)) *MockBudgetService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBudgetService
func (_mock *MockBudgetService) Update(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string) (*domain.Budget, error) {
	ret := _mock.Called(ctx, id, name, method, currency)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string) (*domain.Budget, error)); ok {
		return returnFunc(ctx, id, name, method, currency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.BudgetMethod, string) *domain.Budget); ok {
		r0 = returnFunc(ctx, id, name, method, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.BudgetMethod, string) error); ok {
		r1 = returnFunc(ctx, id, name, method, currency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBudgetService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBudgetService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - method domain.BudgetMethod
//   - currency string
func (_e *MockBudgetService_Expecter) Update(ctx any, id any, name any, method any, currency any) *MockBudgetService_Update_Call {
	return &MockBudgetService_Update_Call{Call: _e.mock.On("Update", ctx, id, name, method, currency)}
}

func (_c *MockBudgetService_Update_Call) Run(run func(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string)) *MockBudgetService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.BudgetMethod
		if args[3] != nil {
			arg3 = args[3].(domain.BudgetMethod)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBudgetService_Update_Call) Return(budget *domain.Budget, err error) *MockBudgetService_Update_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *MockBudgetService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, name string, method domain.BudgetMethod, currency string) (*domain.Budget, error)) *MockBudgetService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Create(ctx context.Context, budgetID string, name string, accType domain.AccountType, balance int64) (*domain.Account, error) {
	ret := _mock.Called(ctx, budgetID, name, accType, balance)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.AccountType, int64) (*domain.Account, error)); ok {
		return returnFunc(ctx, budgetID, name, accType, balance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.AccountType, int64) *domain.Account); ok {
		r0 = returnFunc(ctx, budgetID, name, accType, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.AccountType, int64) error); ok {
		r1 = returnFunc(ctx, budgetID, name, accType, balance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - name string
//   - accType domain.AccountType
//   - balance int64
func (_e *MockAccountService_Expecter) Create(ctx any, budgetID any, name any, accType any, balance any) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", ctx, budgetID, name, accType, balance)}
}

func (_c *MockAccountService_Create_Call) Run(run func(ctx context.Context, budgetID string, name string, accType domain.AccountType, balance int64)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.AccountType
		if args[3] != nil {
			arg3 = args[3].(domain.AccountType)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(account *domain.Account, err error) *MockAccountService_Create_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(ctx context.Context, budgetID string, name string, accType domain.AccountType, balance int64) (*domain.Account, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountService_Expecter) Delete(ctx any, id any) *MockAccountService_Delete_Call {
	return &MockAccountService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAccountService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_Delete_Call) Return(err error) *MockAccountService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAccountService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetByID(ctx context.Context, id string) (*domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountService_Expecter) GetByID(ctx any, id any) *MockAccountService_GetByID_Call {
	return &MockAccountService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockAccountService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_GetByID_Call) Return(account *domain.Account, err error) *MockAccountService_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Account, error)) *MockAccountService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAccountService
func (_mock *MockAccountService) List(ctx context.Context, budgetID string) ([]*domain.Account, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Account, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Account); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAccountService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockAccountService_Expecter) List(ctx any, budgetID any) *MockAccountService_List_Call {
	return &MockAccountService_List_Call{Call: _e.mock.On("List", ctx, budgetID)}
}

func (_c *MockAccountService_List_Call) Run(run func(ctx context.Context, budgetID string)) *MockAccountService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_List_Call) Return(accounts []*domain.Account, err error) *MockAccountService_List_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountService_List_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Account, error)) *MockAccountService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Update(ctx context.Context, acc *domain.Account) (*domain.Account, error) {
	ret := _mock.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Account) (*domain.Account, error)); ok {
		return returnFunc(ctx, acc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Account) *domain.Account); ok {
		r0 = returnFunc(ctx, acc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Account) error); ok {
		r1 = returnFunc(ctx, acc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *domain.Account
func (_e *MockAccountService_Expecter) Update(ctx any, acc any) *MockAccountService_Update_Call {
	return &MockAccountService_Update_Call{Call: _e.mock.On("Update", ctx, acc)}
}

func (_c *MockAccountService_Update_Call) Run(run func(ctx context.Context, acc *domain.Account)) *MockAccountService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Account
		if args[1] != nil {
			arg1 = args[1].(*domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_Update_Call) Return(account *domain.Account, err error) *MockAccountService_Update_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountService_Update_Call) RunAndReturn(run func(ctx context.Context, acc *domain.Account) (*domain.Account, error)) *MockAccountService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// AssignFunds provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) AssignFunds(ctx context.Context, budgetID string, catID string, amount int64) (*domain.Category, error) {
	ret := _mock.Called(ctx, budgetID, catID, amount)

	if len(ret) == 0 {
		panic("no return value specified for AssignFunds")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*domain.Category, error)); ok {
		return returnFunc(ctx, budgetID, catID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *domain.Category); ok {
		r0 = returnFunc(ctx, budgetID, catID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, budgetID, catID, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_AssignFunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignFunds'
type MockCategoryService_AssignFunds_Call struct {
	*mock.Call
}

// AssignFunds is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - catID string
//   - amount int64
func (_e *MockCategoryService_Expecter) AssignFunds(ctx any, budgetID any, catID any, amount any) *MockCategoryService_AssignFunds_Call {
	return &MockCategoryService_AssignFunds_Call{Call: _e.mock.On("AssignFunds", ctx, budgetID, catID, amount)}
}

func (_c *MockCategoryService_AssignFunds_Call) Run(run func(ctx context.Context, budgetID string, catID string, amount int64)) *MockCategoryService_AssignFunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCategoryService_AssignFunds_Call) Return(category *domain.Category, err error) *MockCategoryService_AssignFunds_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_AssignFunds_Call) RunAndReturn(run func(ctx context.Context, budgetID string, catID string, amount int64) (*domain.Category, error)) *MockCategoryService_AssignFunds_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Create(ctx context.Context, budgetID string, name string, targetLimit int64) (*domain.Category, error) {
	ret := _mock.Called(ctx, budgetID, name, targetLimit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*domain.Category, error)); ok {
		return returnFunc(ctx, budgetID, name, targetLimit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *domain.Category); ok {
		r0 = returnFunc(ctx, budgetID, name, targetLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, budgetID, name, targetLimit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - name string
//   - targetLimit int64
func (_e *MockCategoryService_Expecter) Create(ctx any, budgetID any, name any, targetLimit any) *MockCategoryService_Create_Call {
	return &MockCategoryService_Create_Call{Call: _e.mock.On("Create", ctx, budgetID, name, targetLimit)}
}

func (_c *MockCategoryService_Create_Call) Run(run func(ctx context.Context, budgetID string, name string, targetLimit int64)) *MockCategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCategoryService_Create_Call) Return(category *domain.Category, err error) *MockCategoryService_Create_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Create_Call) RunAndReturn(run func(ctx context.Context, budgetID string, name string, targetLimit int64) (*domain.Category, error)) *MockCategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCategoryService_Expecter) Delete(ctx any, id any) *MockCategoryService_Delete_Call {
	return &MockCategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_Delete_Call) Return(err error) *MockCategoryService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockCategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FundEnvelope provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) FundEnvelope(ctx context.Context, budgetID string, catID string, accountID string, amount int64) (*domain.Account, *domain.Category, error) {
	ret := _mock.Called(ctx, budgetID, catID, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for FundEnvelope")
	}

	var r0 *domain.Account
	var r1 *domain.Category
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (*domain.Account, *domain.Category, error)); ok {
		return returnFunc(ctx, budgetID, catID, accountID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) *domain.Account); ok {
		r0 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64) *domain.Category); ok {
		r1 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, int64) error); ok {
		r2 = returnFunc(ctx, budgetID, catID, accountID, amount)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCategoryService_FundEnvelope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundEnvelope'
type MockCategoryService_FundEnvelope_Call struct {
	*mock.Call
}

// FundEnvelope is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - catID string
//   - accountID string
//   - amount int64
func (_e *MockCategoryService_Expecter) FundEnvelope(ctx any, budgetID any, catID any, accountID any, amount any) *MockCategoryService_FundEnvelope_Call {
	return &MockCategoryService_FundEnvelope_Call{Call: _e.mock.On("FundEnvelope", ctx, budgetID, catID, accountID, amount)}
}

func (_c *MockCategoryService_FundEnvelope_Call) Run(run func(ctx context.Context, budgetID string, catID string, accountID string, amount int64)) *MockCategoryService_FundEnvelope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCategoryService_FundEnvelope_Call) Return(account *domain.Account, category *domain.Category, err error) *MockCategoryService_FundEnvelope_Call {
	_c.Call.Return(account, category, err)
	return _c
}

func (_c *MockCategoryService_FundEnvelope_Call) RunAndReturn(run func(ctx context.Context, budgetID string, catID string, accountID string, amount int64) (*domain.Account, *domain.Category, error)) *MockCategoryService_FundEnvelope_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) GetByID(ctx context.Context, id string) (*domain.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCategoryService_Expecter) GetByID(ctx any, id any) *MockCategoryService_GetByID_Call {
	return &MockCategoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCategoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_GetByID_Call) Return(category *domain.Category, err error) *MockCategoryService_GetByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Category, error)) *MockCategoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) List(ctx context.Context, budgetID string) ([]*domain.Category, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Category, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Category); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockCategoryService_Expecter) List(ctx any, budgetID any) *MockCategoryService_List_Call {
	return &MockCategoryService_List_Call{Call: _e.mock.On("List", ctx, budgetID)}
}

func (_c *MockCategoryService_List_Call) Run(run func(ctx context.Context, budgetID string)) *MockCategoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_List_Call) Return(categorys []*domain.Category, err error) *MockCategoryService_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryService_List_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Category, error)) *MockCategoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Update(ctx context.Context, cat *domain.Category) (*domain.Category, error) {
	ret := _mock.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Category) (*domain.Category, error)); ok {
		return returnFunc(ctx, cat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Category) *domain.Category); ok {
		r0 = returnFunc(ctx, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Category) error); ok {
		r1 = returnFunc(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cat *domain.Category
func (_e *MockCategoryService_Expecter) Update(ctx any, cat any) *MockCategoryService_Update_Call {
	return &MockCategoryService_Update_Call{Call: _e.mock.On("Update", ctx, cat)}
}

func (_c *MockCategoryService_Update_Call) Run(run func(ctx context.Context, cat *domain.Category)) *MockCategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Category
		if args[1] != nil {
			arg1 = args[1].(*domain.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_Update_Call) Return(category *domain.Category, err error) *MockCategoryService_Update_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Update_Call) RunAndReturn(run func(ctx context.Context, cat *domain.Category) (*domain.Category, error)) *MockCategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Create(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID, accountID, categoryID, amount, description, date)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, time.Time) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, time.Time) *domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, string, time.Time) error); ok {
		r1 = returnFunc(ctx, budgetID, accountID, categoryID, amount, description, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - accountID string
//   - categoryID string
//   - amount int64
//   - description string
//   - date time.Time
func (_e *MockTransactionService_Expecter) Create(ctx any, budgetID any, accountID any, categoryID any, amount any, description any, date any) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, budgetID, accountID, categoryID, amount, description, date)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(transaction *domain.Transaction, err error) *MockTransactionService_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(ctx context.Context, budgetID string, accountID string, categoryID string, amount int64, description string, date time.Time) (*domain.Transaction, error)) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Delete(ctx context.Context, budgetID string, txID string) error {
	ret := _mock.Called(ctx, budgetID, txID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, budgetID, txID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - txID string
func (_e *MockTransactionService_Expecter) Delete(ctx any, budgetID any, txID any) *MockTransactionService_Delete_Call {
	return &MockTransactionService_Delete_Call{Call: _e.mock.On("Delete", ctx, budgetID, txID)}
}

func (_c *MockTransactionService_Delete_Call) Run(run func(ctx context.Context, budgetID string, txID string)) *MockTransactionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionService_Delete_Call) Return(err error) *MockTransactionService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionService_Delete_Call) RunAndReturn(run func(ctx context.Context, budgetID string, txID string) error) *MockTransactionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) List(ctx context.Context, budgetID string) ([]*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *MockTransactionService_Expecter) List(ctx any, budgetID any) *MockTransactionService_List_Call {
	return &MockTransactionService_List_Call{Call: _e.mock.On("List", ctx, budgetID)}
}

func (_c *MockTransactionService_List_Call) Run(run func(ctx context.Context, budgetID string)) *MockTransactionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionService_List_Call) Return(transactions []*domain.Transaction, err error) *MockTransactionService_List_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionService_List_Call) RunAndReturn(run func(ctx context.Context, budgetID string) ([]*domain.Transaction, error)) *MockTransactionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) Update(ctx context.Context, budgetID string, txID string, updates *domain.Transaction) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, budgetID, txID, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Transaction) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, budgetID, txID, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Transaction) *domain.Transaction); ok {
		r0 = returnFunc(ctx, budgetID, txID, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.Transaction) error); ok {
		r1 = returnFunc(ctx, budgetID, txID, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
//   - txID string
//   - updates *domain.Transaction
func (_e *MockTransactionService_Expecter) Update(ctx any, budgetID any, txID any, updates any) *MockTransactionService_Update_Call {
	return &MockTransactionService_Update_Call{Call: _e.mock.On("Update", ctx, budgetID, txID, updates)}
}

func (_c *MockTransactionService_Update_Call) Run(run func(ctx context.Context, budgetID string, txID string, updates *domain.Transaction)) *MockTransactionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.Transaction
		if args[3] != nil {
			arg3 = args[3].(*domain.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionService_Update_Call) Return(transaction *domain.Transaction, err error) *MockTransactionService_Update_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionService_Update_Call) RunAndReturn(run func(ctx context.Context, budgetID string, txID string, updates *domain.Transaction) (*domain.Transaction, error)) *MockTransactionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBankSyncService creates a new instance of MockBankSyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankSyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankSyncService {
	mock := &MockBankSyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankSyncService is an autogenerated mock type for the BankSyncService type
type MockBankSyncService struct {
	mock.Mock
}

type MockBankSyncService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankSyncService) EXPECT() *MockBankSyncService_Expecter {
	return &MockBankSyncService_Expecter{mock: &_m.Mock}
}

// GetAuthLink provides a mock function for the type MockBankSyncService
func (_mock *MockBankSyncService) GetAuthLink(ctx context.Context, userID string) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthLink")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBankSyncService_GetAuthLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthLink'
type MockBankSyncService_GetAuthLink_Call struct {
	*mock.Call
}

// GetAuthLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBankSyncService_Expecter) GetAuthLink(ctx any, userID any) *MockBankSyncService_GetAuthLink_Call {
	return &MockBankSyncService_GetAuthLink_Call{Call: _e.mock.On("GetAuthLink", ctx, userID)}
}

func (_c *MockBankSyncService_GetAuthLink_Call) Run(run func(ctx context.Context, userID string)) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankSyncService_GetAuthLink_Call) Return(s string, s1 string, err error) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockBankSyncService_GetAuthLink_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, string, error)) *MockBankSyncService_GetAuthLink_Call {
	_c.Call.Return(run)
	return _c
}

// SyncUser provides a mock function for the type MockBankSyncService
func (_mock *MockBankSyncService) SyncUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SyncUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankSyncService_SyncUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncUser'
type MockBankSyncService_SyncUser_Call struct {
	*mock.Call
}

// SyncUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBankSyncService_Expecter) SyncUser(ctx any, userID any) *MockBankSyncService_SyncUser_Call {
	return &MockBankSyncService_SyncUser_Call{Call: _e.mock.On("SyncUser", ctx, userID)}
}

func (_c *MockBankSyncService_SyncUser_Call) Run(run func(ctx context.Context, userID string)) *MockBankSyncService_SyncUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankSyncService_SyncUser_Call) Return(err error) *MockBankSyncService_SyncUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankSyncService_SyncUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockBankSyncService_SyncUser_Call {
	_c.Call.Return(run)
	return _c
}
