import type { Category } from "./types";

/**
 * Reference taxonomy for local/offline mode only.
 * Online users receive the Basiq-aligned tree from the backend
 * (categoryseed/au_basiq.go + migration seed).
 */

type SeedEntry = Omit<Category, "id"> & { seedId: string };

export const DEFAULT_CATEGORIES: SeedEntry[] = [
  // ── Income ─────────────────────────────────────────────────────────────────
  {
    seedId: "income-salary",
    name: "Salary",
    type: "income",
    parentId: null,
    color: "#34d399",
    archived: false,
    sortOrder: 0,
    system: true,
  },
  {
    seedId: "income-freelance",
    name: "Freelance",
    type: "income",
    parentId: null,
    color: "#34d399",
    archived: false,
    sortOrder: 1,
  },
  {
    seedId: "income-invest",
    name: "Investment income",
    type: "income",
    parentId: null,
    color: "#22c1c3",
    archived: false,
    sortOrder: 2,
  },
  {
    seedId: "income-taxreturn",
    name: "Tax return",
    type: "income",
    parentId: null,
    color: "#22c1c3",
    archived: false,
    sortOrder: 3,
  },
  {
    seedId: "income-other",
    name: "Other income",
    type: "income",
    parentId: null,
    color: "#94a3b8",
    archived: false,
    sortOrder: 4,
  },

  // ── Expense ─────────────────────────────────────────────────────────────────
  {
    seedId: "exp-housing",
    name: "Housing",
    type: "expense",
    parentId: null,
    color: "#7c5cff",
    archived: false,
    sortOrder: 0,
  },
  {
    seedId: "exp-rent",
    name: "Rent / Mortgage",
    type: "expense",
    parentId: "exp-housing",
    color: "#7c5cff",
    archived: false,
    sortOrder: 0,
    system: true,
  },
  {
    seedId: "exp-utilities",
    name: "Utilities",
    type: "expense",
    parentId: "exp-housing",
    color: "#7c5cff",
    archived: false,
    sortOrder: 1,
  },
  {
    seedId: "exp-groceries",
    name: "Groceries",
    type: "expense",
    parentId: null,
    color: "#f5b942",
    archived: false,
    sortOrder: 1,
  },
  {
    seedId: "exp-dining",
    name: "Dining & takeaway",
    type: "expense",
    parentId: null,
    color: "#fb7185",
    archived: false,
    sortOrder: 2,
  },
  {
    seedId: "exp-transport",
    name: "Transport",
    type: "expense",
    parentId: null,
    color: "#60a5fa",
    archived: false,
    sortOrder: 3,
  },
  {
    seedId: "exp-fuel",
    name: "Fuel",
    type: "expense",
    parentId: "exp-transport",
    color: "#60a5fa",
    archived: false,
    sortOrder: 0,
  },
  {
    seedId: "exp-publictrans",
    name: "Public transport",
    type: "expense",
    parentId: "exp-transport",
    color: "#60a5fa",
    archived: false,
    sortOrder: 1,
  },
  {
    seedId: "exp-insurance",
    name: "Insurance",
    type: "expense",
    parentId: null,
    color: "#a78bfa",
    archived: false,
    sortOrder: 4,
  },
  {
    seedId: "exp-health",
    name: "Health & medical",
    type: "expense",
    parentId: null,
    color: "#ef4f6c",
    archived: false,
    sortOrder: 5,
  },
  {
    seedId: "exp-entertainment",
    name: "Entertainment",
    type: "expense",
    parentId: null,
    color: "#f97316",
    archived: false,
    sortOrder: 6,
  },
  {
    seedId: "exp-subscriptions",
    name: "Subscriptions",
    type: "expense",
    parentId: "exp-entertainment",
    color: "#f97316",
    archived: false,
    sortOrder: 0,
  },
  {
    seedId: "exp-clothing",
    name: "Clothing",
    type: "expense",
    parentId: null,
    color: "#e879f9",
    archived: false,
    sortOrder: 7,
  },
  {
    seedId: "exp-personal",
    name: "Personal care",
    type: "expense",
    parentId: null,
    color: "#4ade80",
    archived: false,
    sortOrder: 8,
  },
  {
    seedId: "exp-education",
    name: "Education",
    type: "expense",
    parentId: null,
    color: "#22c1c3",
    archived: false,
    sortOrder: 9,
  },
  {
    seedId: "exp-travel",
    name: "Travel & holidays",
    type: "expense",
    parentId: null,
    color: "#fb7185",
    archived: false,
    sortOrder: 10,
  },
  {
    seedId: "exp-gifts",
    name: "Gifts & charity",
    type: "expense",
    parentId: null,
    color: "#f5b942",
    archived: false,
    sortOrder: 11,
  },
  {
    seedId: "exp-fees",
    name: "Fees & charges",
    type: "expense",
    parentId: null,
    color: "#94a3b8",
    archived: false,
    sortOrder: 12,
  },
  {
    seedId: "exp-other",
    name: "Other expense",
    type: "expense",
    parentId: null,
    color: "#94a3b8",
    archived: false,
    sortOrder: 13,
  },

  // ── Transfer ────────────────────────────────────────────────────────────────
  {
    seedId: "xfer-savings",
    name: "Savings transfer",
    type: "transfer",
    parentId: null,
    color: "#60a5fa",
    archived: false,
    sortOrder: 0,
  },
  {
    seedId: "xfer-investment",
    name: "Investment",
    type: "transfer",
    parentId: null,
    color: "#34d399",
    archived: false,
    sortOrder: 1,
  },
  {
    seedId: "xfer-debt",
    name: "Debt repayment",
    type: "transfer",
    parentId: null,
    color: "#a78bfa",
    archived: false,
    sortOrder: 2,
  },
];
