// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type AccountMapperHelper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Account, *pkg_budgeting_system_internal_gen_budgy_v1.Account) error
}

type AccountMapper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Account, *pkg_budgeting_system_internal_gen_budgy_v1.Account) error
}

var _ AccountMapper = &accountmapper{}

func NewAccountMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) AccountMapper {
	m := &accountmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.AccountMapperHelper")
	if err == nil {
		m.helper = helper.(AccountMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "budgeting_system/internal/domain#AccountType", "budgeting_system/internal/gen/budgy/v1#AccountType"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_budgeting_system_internal_domain.AccountType) (pkg_budgeting_system_internal_gen_budgy_v1.AccountType, bool, error)); ok {
			m.converter00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)); ok {
			m.converter00001 = v
		}
	}
	return m
}

type accountmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         AccountMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error
	converter00000 func(pkg_context.Context, *pkg_budgeting_system_internal_domain.AccountType) (pkg_budgeting_system_internal_gen_budgy_v1.AccountType, bool, error)
	converter00001 func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)
}

func (m *accountmapper) ToProto(ctx pkg_context.Context, source *pkg_budgeting_system_internal_domain.Account, dest *pkg_budgeting_system_internal_gen_budgy_v1.Account) error {
	dest.Id = source.ID
	dest.BudgetId = source.BudgetID
	dest.Name = source.Name
	done3 := false
	if m.converter00000 != nil && !done3 {
		done3 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Type)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Type = converted
			}
		}
	}
	dest.Balance = source.Balance
	done5 := false
	if m.converter00001 != nil && !done5 {
		done5 = true
		if converted, err := m.converter00001(ctx, &(source.CreatedAt)); err != nil {
			return err
		} else {
			dest.CreatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done5 {
		done5 = true
		if dest.CreatedAt == nil {
			dest.CreatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.CreatedAt), dest.CreatedAt); err != nil {
			return err
		}
	}
	done6 := false
	if m.converter00001 != nil && !done6 {
		done6 = true
		if converted, err := m.converter00001(ctx, &(source.UpdatedAt)); err != nil {
			return err
		} else {
			dest.UpdatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done6 {
		done6 = true
		if dest.UpdatedAt == nil {
			dest.UpdatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.UpdatedAt), dest.UpdatedAt); err != nil {
			return err
		}
	}
	dest.Class = source.Class
	dest.AccountNo = source.AccountNo
	dest.AvailableFunds = source.AvailableFunds
	dest.Product = source.Product
	dest.InstitutionId = source.InstitutionID
	dest.ConnectionId = source.ConnectionID
	done13 := false
	if m.converter00001 != nil && !done13 {
		done13 = true
		if converted, err := m.converter00001(ctx, source.LastUpdated); err != nil {
			return err
		} else {
			dest.LastUpdated = converted
		}
	}
	if m.mapper00000 != nil && source.LastUpdated != nil && !done13 {
		done13 = true
		if dest.LastUpdated == nil {
			dest.LastUpdated = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, source.LastUpdated, dest.LastUpdated); err != nil {
			return err
		}
	}
	if m.helper != nil {
		if err := m.helper.ToProto(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
