// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type BudgetMapperHelper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Budget, *pkg_budgeting_system_internal_gen_budgy_v1.Budget) error
}

type BudgetMapper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Budget, *pkg_budgeting_system_internal_gen_budgy_v1.Budget) error
}

var _ BudgetMapper = &budgetmapper{}

func NewBudgetMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) BudgetMapper {
	m := &budgetmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.BudgetMapperHelper")
	if err == nil {
		m.helper = helper.(BudgetMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "budgeting_system/internal/domain#BudgetMethod", "budgeting_system/internal/gen/budgy/v1#BudgetMethod"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_budgeting_system_internal_domain.BudgetMethod) (pkg_budgeting_system_internal_gen_budgy_v1.BudgetMethod, bool, error)); ok {
			m.converter00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "budgeting_system/internal/domain#BudgetPeriod", "budgeting_system/internal/gen/budgy/v1#BudgetPeriod"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_budgeting_system_internal_domain.BudgetPeriod) (pkg_budgeting_system_internal_gen_budgy_v1.BudgetPeriod, bool, error)); ok {
			m.converter00001 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)); ok {
			m.converter00002 = v
		}
	}
	return m
}

type budgetmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         BudgetMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error
	converter00000 func(pkg_context.Context, *pkg_budgeting_system_internal_domain.BudgetMethod) (pkg_budgeting_system_internal_gen_budgy_v1.BudgetMethod, bool, error)
	converter00001 func(pkg_context.Context, *pkg_budgeting_system_internal_domain.BudgetPeriod) (pkg_budgeting_system_internal_gen_budgy_v1.BudgetPeriod, bool, error)
	converter00002 func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)
}

func (m *budgetmapper) ToProto(ctx pkg_context.Context, source *pkg_budgeting_system_internal_domain.Budget, dest *pkg_budgeting_system_internal_gen_budgy_v1.Budget) error {
	dest.Id = source.ID
	dest.UserId = source.UserID
	dest.Name = source.Name
	done3 := false
	if m.converter00000 != nil && !done3 {
		done3 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Method)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Method = converted
			}
		}
	}
	dest.Currency = source.Currency
	done5 := false
	if m.converter00001 != nil && !done5 {
		done5 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.Period)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Period = converted
			}
		}
	}
	dest.StartDate = source.StartDate
	done7 := false
	if m.converter00002 != nil && !done7 {
		done7 = true
		if converted, err := m.converter00002(ctx, &(source.CreatedAt)); err != nil {
			return err
		} else {
			dest.CreatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done7 {
		done7 = true
		if dest.CreatedAt == nil {
			dest.CreatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.CreatedAt), dest.CreatedAt); err != nil {
			return err
		}
	}
	done8 := false
	if m.converter00002 != nil && !done8 {
		done8 = true
		if converted, err := m.converter00002(ctx, &(source.UpdatedAt)); err != nil {
			return err
		} else {
			dest.UpdatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done8 {
		done8 = true
		if dest.UpdatedAt == nil {
			dest.UpdatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.UpdatedAt), dest.UpdatedAt); err != nil {
			return err
		}
	}
	if m.helper != nil {
		if err := m.helper.ToProto(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
