// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type CategoryMapperHelper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Category, *pkg_budgeting_system_internal_gen_budgy_v1.Category) error
}

type CategoryMapper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Category, *pkg_budgeting_system_internal_gen_budgy_v1.Category) error
}

var _ CategoryMapper = &categorymapper{}

func NewCategoryMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) CategoryMapper {
	m := &categorymapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.CategoryMapperHelper")
	if err == nil {
		m.helper = helper.(CategoryMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type categorymapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         CategoryMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error
	converter00000 func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)
}

func (m *categorymapper) ToProto(ctx pkg_context.Context, source *pkg_budgeting_system_internal_domain.Category, dest *pkg_budgeting_system_internal_gen_budgy_v1.Category) error {
	dest.Id = source.ID
	dest.BudgetId = source.BudgetID
	dest.Name = source.Name
	dest.Budgeted = source.Budgeted
	dest.Balance = source.Balance
	dest.TargetLimit = source.TargetLimit
	done6 := false
	if m.converter00000 != nil && !done6 {
		done6 = true
		if converted, err := m.converter00000(ctx, &(source.CreatedAt)); err != nil {
			return err
		} else {
			dest.CreatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done6 {
		done6 = true
		if dest.CreatedAt == nil {
			dest.CreatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.CreatedAt), dest.CreatedAt); err != nil {
			return err
		}
	}
	done7 := false
	if m.converter00000 != nil && !done7 {
		done7 = true
		if converted, err := m.converter00000(ctx, &(source.UpdatedAt)); err != nil {
			return err
		} else {
			dest.UpdatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done7 {
		done7 = true
		if dest.UpdatedAt == nil {
			dest.UpdatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.UpdatedAt), dest.UpdatedAt); err != nil {
			return err
		}
	}
	if m.helper != nil {
		if err := m.helper.ToProto(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
