// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_storage_db "budgeting_system/internal/storage/db"
	pkg_context "context"
	pkg_database_sql "database/sql"
	"reflect"
	pkg_time "time"
)

type DBAccountMapperHelper interface {
	AccountToAccount(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Account, *pkg_budgeting_system_internal_domain.Account) error
}

type DBAccountMapper interface {
	AccountToAccount(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Account, *pkg_budgeting_system_internal_domain.Account) error
}

var _ DBAccountMapper = &dbaccountmapper{}

func NewDBAccountMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) DBAccountMapper {
	m := &dbaccountmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.DBAccountMapperHelper")
	if err == nil {
		m.helper = helper.(DBAccountMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullTime", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullTime, *pkg_time.Time) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "string", "budgeting_system/internal/domain#AccountType"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *string) (pkg_budgeting_system_internal_domain.AccountType, bool, error)); ok {
			m.converter00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullString", "string"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)); ok {
			m.converter00001 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullInt64", "int64"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullInt64) (int64, bool, error)); ok {
			m.converter00002 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullTime", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullTime) (*pkg_time.Time, error)); ok {
			m.converter00003 = v
		}
	}
	return m
}

type dbaccountmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         DBAccountMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_database_sql.NullTime, *pkg_time.Time) error
	converter00000 func(pkg_context.Context, *string) (pkg_budgeting_system_internal_domain.AccountType, bool, error)
	converter00001 func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)
	converter00002 func(pkg_context.Context, *pkg_database_sql.NullInt64) (int64, bool, error)
	converter00003 func(pkg_context.Context, *pkg_database_sql.NullTime) (*pkg_time.Time, error)
}

func (m *dbaccountmapper) AccountToAccount(ctx pkg_context.Context, source *pkg_budgeting_system_internal_storage_db.Account, dest *pkg_budgeting_system_internal_domain.Account) error {
	dest.ID = source.ID
	dest.UserID = source.UserID
	dest.Name = source.Name
	done3 := false
	if m.converter00000 != nil && !done3 {
		done3 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Type)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Type = converted
			}
		}
	}
	if !done3 {
		done3 = true
		dest.Type = pkg_budgeting_system_internal_domain.AccountType(source.Type)
	}
	dest.Balance = source.Balance
	dest.CreatedAt = source.CreatedAt
	dest.UpdatedAt = source.UpdatedAt
	done8 := false
	if m.converter00001 != nil && !done8 {
		done8 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.Class)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Class = converted
			}
		}
	}
	done9 := false
	if m.converter00001 != nil && !done9 {
		done9 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.AccountNo)); err != nil {
			return err
		} else {
			if !isnil {
				dest.AccountNo = converted
			}
		}
	}
	done10 := false
	if m.converter00002 != nil && !done10 {
		done10 = true
		if converted, isnil, err := m.converter00002(ctx, &(source.AvailableFunds)); err != nil {
			return err
		} else {
			if isnil {
				dest.AvailableFunds = nil
			} else {
				dest.AvailableFunds = &converted
			}
		}
	}
	done11 := false
	if m.converter00001 != nil && !done11 {
		done11 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.Product)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Product = converted
			}
		}
	}
	done12 := false
	if m.converter00001 != nil && !done12 {
		done12 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.InstitutionID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.InstitutionID = converted
			}
		}
	}
	done13 := false
	if m.converter00001 != nil && !done13 {
		done13 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.ConnectionID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.ConnectionID = converted
			}
		}
	}
	done14 := false
	if m.converter00003 != nil && !done14 {
		done14 = true
		if converted, err := m.converter00003(ctx, &(source.LastUpdated)); err != nil {
			return err
		} else {
			dest.LastUpdated = converted
		}
	}
	if m.mapper00000 != nil && !done14 {
		done14 = true
		if dest.LastUpdated == nil {
			dest.LastUpdated = new(pkg_time.Time)
		}
		if err := m.mapper00000(ctx, &(source.LastUpdated), dest.LastUpdated); err != nil {
			return err
		}
	}
	if m.helper != nil {
		if err := m.helper.AccountToAccount(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
