// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_storage_db "budgeting_system/internal/storage/db"
	pkg_context "context"
	pkg_database_sql "database/sql"
	"reflect"
)

type DBCategoryMapperHelper interface {
	CategoryToCategory(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Category, *pkg_budgeting_system_internal_domain.Category) error
}

type DBCategoryMapper interface {
	CategoryToCategory(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Category, *pkg_budgeting_system_internal_domain.Category) error
}

var _ DBCategoryMapper = &dbcategorymapper{}

func NewDBCategoryMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) DBCategoryMapper {
	m := &dbcategorymapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.DBCategoryMapperHelper")
	if err == nil {
		m.helper = helper.(DBCategoryMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullString", "string"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type dbcategorymapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         DBCategoryMapperHelper
	converter00000 func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)
}

func (m *dbcategorymapper) CategoryToCategory(ctx pkg_context.Context, source *pkg_budgeting_system_internal_storage_db.Category, dest *pkg_budgeting_system_internal_domain.Category) error {
	dest.ID = source.ID
	done1 := false
	if m.converter00000 != nil && !done1 {
		done1 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.BudgetID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.BudgetID = converted
			}
		}
	}
	dest.Name = source.Name
	dest.Budgeted = source.Budgeted
	dest.Balance = source.Balance
	dest.TargetLimit = source.TargetLimit
	dest.CreatedAt = source.CreatedAt
	dest.UpdatedAt = source.UpdatedAt
	if m.helper != nil {
		if err := m.helper.CategoryToCategory(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
