// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_storage_db "budgeting_system/internal/storage/db"
	pkg_context "context"
	pkg_database_sql "database/sql"
	"reflect"
)

type DBJobMapperHelper interface {
	BackgroundJobToJob(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.BackgroundJob, *pkg_budgeting_system_internal_domain.Job) error
}

type DBJobMapper interface {
	BackgroundJobToJob(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.BackgroundJob, *pkg_budgeting_system_internal_domain.Job) error
}

var _ DBJobMapper = &dbjobmapper{}

func NewDBJobMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) DBJobMapper {
	m := &dbjobmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.DBJobMapperHelper")
	if err == nil {
		m.helper = helper.(DBJobMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "string", "budgeting_system/internal/domain#JobStatus"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *string) (pkg_budgeting_system_internal_domain.JobStatus, bool, error)); ok {
			m.converter00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "int32", "int"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *int32) (int, bool, error)); ok {
			m.converter00001 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullString", "string"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)); ok {
			m.converter00002 = v
		}
	}
	return m
}

type dbjobmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         DBJobMapperHelper
	converter00000 func(pkg_context.Context, *string) (pkg_budgeting_system_internal_domain.JobStatus, bool, error)
	converter00001 func(pkg_context.Context, *int32) (int, bool, error)
	converter00002 func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)
}

func (m *dbjobmapper) BackgroundJobToJob(ctx pkg_context.Context, source *pkg_budgeting_system_internal_storage_db.BackgroundJob, dest *pkg_budgeting_system_internal_domain.Job) error {
	dest.ID = source.ID
	dest.JobType = source.JobType
	dest.Payload = source.Payload
	done3 := false
	if m.converter00000 != nil && !done3 {
		done3 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Status)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Status = converted
			}
		}
	}
	if !done3 {
		done3 = true
		dest.Status = pkg_budgeting_system_internal_domain.JobStatus(source.Status)
	}
	done5 := false
	if m.converter00001 != nil && !done5 {
		done5 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.Attempts)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Attempts = converted
			}
		}
	}
	done6 := false
	if m.converter00001 != nil && !done6 {
		done6 = true
		if converted, isnil, err := m.converter00001(ctx, &(source.MaxAttempts)); err != nil {
			return err
		} else {
			if !isnil {
				dest.MaxAttempts = converted
			}
		}
	}
	dest.RunAt = source.RunAt
	done8 := false
	if m.converter00002 != nil && !done8 {
		done8 = true
		if converted, isnil, err := m.converter00002(ctx, &(source.ErrorMessage)); err != nil {
			return err
		} else {
			if isnil {
				dest.ErrorMessage = nil
			} else {
				dest.ErrorMessage = &converted
			}
		}
	}
	dest.CreatedAt = source.CreatedAt
	dest.UpdatedAt = source.UpdatedAt
	if m.helper != nil {
		if err := m.helper.BackgroundJobToJob(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
