// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_storage_db "budgeting_system/internal/storage/db"
	pkg_context "context"
	pkg_database_sql "database/sql"
	"reflect"
	pkg_time "time"
)

type DBTransactionMapperHelper interface {
	TransactionToTransaction(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Transaction, *pkg_budgeting_system_internal_domain.Transaction) error
}

type DBTransactionMapper interface {
	TransactionToTransaction(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.Transaction, *pkg_budgeting_system_internal_domain.Transaction) error
}

var _ DBTransactionMapper = &dbtransactionmapper{}

func NewDBTransactionMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) DBTransactionMapper {
	m := &dbtransactionmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.DBTransactionMapperHelper")
	if err == nil {
		m.helper = helper.(DBTransactionMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullTime", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullTime, *pkg_time.Time) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullString", "string"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)); ok {
			m.converter00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullTime", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullTime) (*pkg_time.Time, error)); ok {
			m.converter00001 = v
		}
	}
	return m
}

type dbtransactionmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         DBTransactionMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_database_sql.NullTime, *pkg_time.Time) error
	converter00000 func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)
	converter00001 func(pkg_context.Context, *pkg_database_sql.NullTime) (*pkg_time.Time, error)
}

func (m *dbtransactionmapper) TransactionToTransaction(ctx pkg_context.Context, source *pkg_budgeting_system_internal_storage_db.Transaction, dest *pkg_budgeting_system_internal_domain.Transaction) error {
	dest.ID = source.ID
	dest.AccountID = source.AccountID
	done2 := false
	if m.converter00000 != nil && !done2 {
		done2 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.CategoryID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.CategoryID = converted
			}
		}
	}
	done3 := false
	if m.converter00000 != nil && !done3 {
		done3 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.CustomerCategoryID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.CustomerCategoryID = converted
			}
		}
	}
	dest.Amount = source.Amount
	dest.Description = source.Description
	dest.Date = source.Date
	dest.CreatedAt = source.CreatedAt
	dest.UpdatedAt = source.UpdatedAt
	done9 := false
	if m.converter00000 != nil && !done9 {
		done9 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Direction)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Direction = converted
			}
		}
	}
	done10 := false
	if m.converter00000 != nil && !done10 {
		done10 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Status)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Status = converted
			}
		}
	}
	done11 := false
	if m.converter00000 != nil && !done11 {
		done11 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.Class)); err != nil {
			return err
		} else {
			if !isnil {
				dest.Class = converted
			}
		}
	}
	done12 := false
	if m.converter00001 != nil && !done12 {
		done12 = true
		if converted, err := m.converter00001(ctx, &(source.PostDate)); err != nil {
			return err
		} else {
			dest.PostDate = converted
		}
	}
	if m.mapper00000 != nil && !done12 {
		done12 = true
		if dest.PostDate == nil {
			dest.PostDate = new(pkg_time.Time)
		}
		if err := m.mapper00000(ctx, &(source.PostDate), dest.PostDate); err != nil {
			return err
		}
	}
	done13 := false
	if m.converter00000 != nil && !done13 {
		done13 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.SubClass)); err != nil {
			return err
		} else {
			if !isnil {
				dest.SubClass = converted
			}
		}
	}
	done14 := false
	if m.converter00000 != nil && !done14 {
		done14 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.RawDescription)); err != nil {
			return err
		} else {
			if !isnil {
				dest.RawDescription = converted
			}
		}
	}
	done15 := false
	if m.converter00000 != nil && !done15 {
		done15 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.MerchantName)); err != nil {
			return err
		} else {
			if !isnil {
				dest.MerchantName = converted
			}
		}
	}
	done16 := false
	if m.converter00000 != nil && !done16 {
		done16 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.MerchantWebsite)); err != nil {
			return err
		} else {
			if !isnil {
				dest.MerchantWebsite = converted
			}
		}
	}
	done17 := false
	if m.converter00000 != nil && !done17 {
		done17 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.MerchantLogoUrl)); err != nil {
			return err
		} else {
			if !isnil {
				dest.MerchantLogoURL = converted
			}
		}
	}
	done18 := false
	if m.converter00000 != nil && !done18 {
		done18 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.LocationAddress)); err != nil {
			return err
		} else {
			if !isnil {
				dest.LocationAddress = converted
			}
		}
	}
	done19 := false
	if m.converter00000 != nil && !done19 {
		done19 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.LocationLat)); err != nil {
			return err
		} else {
			if !isnil {
				dest.LocationLat = converted
			}
		}
	}
	done20 := false
	if m.converter00000 != nil && !done20 {
		done20 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.LocationLng)); err != nil {
			return err
		} else {
			if !isnil {
				dest.LocationLng = converted
			}
		}
	}
	done21 := false
	if m.converter00000 != nil && !done21 {
		done21 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.CategoryCode)); err != nil {
			return err
		} else {
			if !isnil {
				dest.CategoryCode = converted
			}
		}
	}
	done22 := false
	if m.converter00000 != nil && !done22 {
		done22 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.CategoryTitle)); err != nil {
			return err
		} else {
			if !isnil {
				dest.CategoryTitle = converted
			}
		}
	}
	if m.helper != nil {
		if err := m.helper.TransactionToTransaction(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
