// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_storage_db "budgeting_system/internal/storage/db"
	pkg_context "context"
	pkg_database_sql "database/sql"
	"reflect"
)

type DBUserMapperHelper interface {
	UserToUser(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.User, *pkg_budgeting_system_internal_domain.User) error
}

type DBUserMapper interface {
	UserToUser(pkg_context.Context, *pkg_budgeting_system_internal_storage_db.User, *pkg_budgeting_system_internal_domain.User) error
}

var _ DBUserMapper = &dbusermapper{}

func NewDBUserMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) DBUserMapper {
	m := &dbusermapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.DBUserMapperHelper")
	if err == nil {
		m.helper = helper.(DBUserMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "database/sql#NullString", "string"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type dbusermapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         DBUserMapperHelper
	converter00000 func(pkg_context.Context, *pkg_database_sql.NullString) (string, bool, error)
}

func (m *dbusermapper) UserToUser(ctx pkg_context.Context, source *pkg_budgeting_system_internal_storage_db.User, dest *pkg_budgeting_system_internal_domain.User) error {
	dest.ID = source.ID
	dest.Email = source.Email
	dest.PasswordHash = source.PasswordHash
	dest.FirstName = source.FirstName
	dest.LastName = source.LastName
	done5 := false
	if m.converter00000 != nil && !done5 {
		done5 = true
		if converted, isnil, err := m.converter00000(ctx, &(source.BasiqUserID)); err != nil {
			return err
		} else {
			if !isnil {
				dest.BasiqUserID = converted
			}
		}
	}
	dest.CreatedAt = source.CreatedAt
	dest.UpdatedAt = source.UpdatedAt
	if m.helper != nil {
		if err := m.helper.UserToUser(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
