// Code generated by sesame; DO NOT EDIT.

package mappings

import (
	"reflect"

	"github.com/yuin/sesame"
)

// NewMappers return a new [sesame.Mappers] .
// Mappers are goroutine safe for get actions.
// Mappers are not goroutine safe for add/merge actions.
func NewMappers() sesame.Mappers {
	mappers := sesame.NewMappers()
	mappers.AddFactory("budgeting_system/internal/mappings.TransactionMapper", reflect.TypeOf((*TransactionMapper)(nil)).Elem(), func(ms sesame.MapperGetter) (any, error) {
		return NewTransactionMapper(ms), nil
	})
	return mappers
}
