// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type TransactionProtoMapperHelper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Transaction, *pkg_budgeting_system_internal_gen_budgy_v1.Transaction) error
}

type TransactionProtoMapper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.Transaction, *pkg_budgeting_system_internal_gen_budgy_v1.Transaction) error
}

var _ TransactionProtoMapper = &transactionprotomapper{}

func NewTransactionProtoMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) TransactionProtoMapper {
	m := &transactionprotomapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.TransactionProtoMapperHelper")
	if err == nil {
		m.helper = helper.(TransactionProtoMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type transactionprotomapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         TransactionProtoMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error
	converter00000 func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)
}

func (m *transactionprotomapper) ToProto(ctx pkg_context.Context, source *pkg_budgeting_system_internal_domain.Transaction, dest *pkg_budgeting_system_internal_gen_budgy_v1.Transaction) error {
	dest.Id = source.ID
	dest.BudgetId = source.BudgetID
	dest.AccountId = source.AccountID
	dest.CategoryId = source.CategoryID
	dest.Amount = source.Amount
	dest.Description = source.Description
	done6 := false
	if m.converter00000 != nil && !done6 {
		done6 = true
		if converted, err := m.converter00000(ctx, &(source.Date)); err != nil {
			return err
		} else {
			dest.Date = converted
		}
	}
	if m.mapper00000 != nil && !done6 {
		done6 = true
		if dest.Date == nil {
			dest.Date = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.Date), dest.Date); err != nil {
			return err
		}
	}
	done7 := false
	if m.converter00000 != nil && !done7 {
		done7 = true
		if converted, err := m.converter00000(ctx, &(source.CreatedAt)); err != nil {
			return err
		} else {
			dest.CreatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done7 {
		done7 = true
		if dest.CreatedAt == nil {
			dest.CreatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.CreatedAt), dest.CreatedAt); err != nil {
			return err
		}
	}
	done8 := false
	if m.converter00000 != nil && !done8 {
		done8 = true
		if converted, err := m.converter00000(ctx, &(source.UpdatedAt)); err != nil {
			return err
		} else {
			dest.UpdatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done8 {
		done8 = true
		if dest.UpdatedAt == nil {
			dest.UpdatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.UpdatedAt), dest.UpdatedAt); err != nil {
			return err
		}
	}
	dest.Direction = source.Direction
	dest.Status = source.Status
	dest.Class = source.Class
	done12 := false
	if m.converter00000 != nil && !done12 {
		done12 = true
		if converted, err := m.converter00000(ctx, source.PostDate); err != nil {
			return err
		} else {
			dest.PostDate = converted
		}
	}
	if m.mapper00000 != nil && source.PostDate != nil && !done12 {
		done12 = true
		if dest.PostDate == nil {
			dest.PostDate = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, source.PostDate, dest.PostDate); err != nil {
			return err
		}
	}
	dest.SubClass = source.SubClass
	dest.RawDescription = source.RawDescription
	dest.MerchantName = source.MerchantName
	dest.MerchantWebsite = source.MerchantWebsite
	dest.MerchantLogoUrl = source.MerchantLogoURL
	dest.LocationAddress = source.LocationAddress
	dest.LocationLat = source.LocationLat
	dest.LocationLng = source.LocationLng
	dest.CategoryCode = source.CategoryCode
	dest.CategoryTitle = source.CategoryTitle
	if m.helper != nil {
		if err := m.helper.ToProto(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
