// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type TransactionMapperHelper interface {
	UpdateTransactionRequestToTransaction(pkg_context.Context, *pkg_budgeting_system_internal_gen_budgy_v1.UpdateTransactionRequest, *pkg_budgeting_system_internal_domain.Transaction) error
}

type TransactionMapper interface {
	UpdateTransactionRequestToTransaction(pkg_context.Context, *pkg_budgeting_system_internal_gen_budgy_v1.UpdateTransactionRequest, *pkg_budgeting_system_internal_domain.Transaction) error
}

var _ TransactionMapper = &transactionmapper{}

func NewTransactionMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) TransactionMapper {
	m := &transactionmapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.TransactionMapperHelper")
	if err == nil {
		m.helper = helper.(TransactionMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "google.golang.org/protobuf/types/known/timestamppb#Timestamp", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, *pkg_time.Time) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "google.golang.org/protobuf/types/known/timestamppb#Timestamp", "time#Time"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) (*pkg_time.Time, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type transactionmapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         TransactionMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, *pkg_time.Time) error
	converter00000 func(pkg_context.Context, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) (*pkg_time.Time, error)
}

func (m *transactionmapper) UpdateTransactionRequestToTransaction(ctx pkg_context.Context, source *pkg_budgeting_system_internal_gen_budgy_v1.UpdateTransactionRequest, dest *pkg_budgeting_system_internal_domain.Transaction) error {
	dest.BudgetID = source.BudgetId
	if (source.AccountId) != nil {
		dest.AccountID = *(source.AccountId)
	}
	if (source.CategoryId) != nil {
		dest.CategoryID = *(source.CategoryId)
	}
	if (source.Amount) != nil {
		dest.Amount = *(source.Amount)
	}
	if (source.Description) != nil {
		dest.Description = *(source.Description)
	}
	done5 := false
	if m.converter00000 != nil && !done5 {
		done5 = true
		if converted, err := m.converter00000(ctx, source.Date); err != nil {
			return err
		} else {
			if converted != nil {
				dest.Date = *converted
			}
		}
	}
	if m.mapper00000 != nil && source.Date != nil && !done5 {
		done5 = true
		if err := m.mapper00000(ctx, source.Date, &(dest.Date)); err != nil {
			return err
		}
	}
	if (source.Direction) != nil {
		dest.Direction = *(source.Direction)
	}
	if (source.Status) != nil {
		dest.Status = *(source.Status)
	}
	if (source.Class) != nil {
		dest.Class = *(source.Class)
	}
	done9 := false
	if m.converter00000 != nil && !done9 {
		done9 = true
		if converted, err := m.converter00000(ctx, source.PostDate); err != nil {
			return err
		} else {
			dest.PostDate = converted
		}
	}
	if m.mapper00000 != nil && source.PostDate != nil && !done9 {
		done9 = true
		if dest.PostDate == nil {
			dest.PostDate = new(pkg_time.Time)
		}
		if err := m.mapper00000(ctx, source.PostDate, dest.PostDate); err != nil {
			return err
		}
	}
	if (source.SubClass) != nil {
		dest.SubClass = *(source.SubClass)
	}
	if (source.RawDescription) != nil {
		dest.RawDescription = *(source.RawDescription)
	}
	if (source.MerchantName) != nil {
		dest.MerchantName = *(source.MerchantName)
	}
	if (source.MerchantWebsite) != nil {
		dest.MerchantWebsite = *(source.MerchantWebsite)
	}
	if (source.MerchantLogoUrl) != nil {
		dest.MerchantLogoURL = *(source.MerchantLogoUrl)
	}
	if (source.LocationAddress) != nil {
		dest.LocationAddress = *(source.LocationAddress)
	}
	if (source.LocationLat) != nil {
		dest.LocationLat = *(source.LocationLat)
	}
	if (source.LocationLng) != nil {
		dest.LocationLng = *(source.LocationLng)
	}
	if (source.CategoryCode) != nil {
		dest.CategoryCode = *(source.CategoryCode)
	}
	if (source.CategoryTitle) != nil {
		dest.CategoryTitle = *(source.CategoryTitle)
	}
	if m.helper != nil {
		if err := m.helper.UpdateTransactionRequestToTransaction(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
