// Code generated by sesame; DO NOT EDIT.
package mappings

import (
	pkg_budgeting_system_internal_domain "budgeting_system/internal/domain"
	pkg_budgeting_system_internal_gen_budgy_v1 "budgeting_system/internal/gen/budgy/v1"
	pkg_context "context"
	"reflect"
	pkg_time "time"

	pkg_google_golang_org_protobuf_types_known_timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type UserMapperHelper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.User, *pkg_budgeting_system_internal_gen_budgy_v1.User) error
}

type UserMapper interface {
	ToProto(pkg_context.Context, *pkg_budgeting_system_internal_domain.User, *pkg_budgeting_system_internal_gen_budgy_v1.User) error
}

var _ UserMapper = &usermapper{}

func NewUserMapper(mapperGetter interface {
	Get(id string) (any, error)
	GetAllMappers() (map[string]any, error)
	GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
	GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
}) UserMapper {
	m := &usermapper{
		mapperGetter: mapperGetter,
	}
	helper, err := m.mapperGetter.Get("budgeting_system/internal/mappings.UserMapperHelper")
	if err == nil {
		m.helper = helper.(UserMapperHelper)
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error); ok {
			m.mapper00000 = v
		}
	}
	if obj, err := mapperGetter.GetFuncByTypeName("", "time#Time", "google.golang.org/protobuf/types/known/timestamppb#Timestamp"); err == nil {
		if v, ok := obj.(func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)); ok {
			m.converter00000 = v
		}
	}
	return m
}

type usermapper struct {
	mapperGetter interface {
		Get(id string) (any, error)
		GetAllMappers() (map[string]any, error)
		GetFunc(id string, sourceType reflect.Type, destType reflect.Type) (any, error)
		GetFuncByTypeName(id string, sourceName string, destName string) (any, error)
	}
	helper         UserMapperHelper
	mapper00000    func(pkg_context.Context, *pkg_time.Time, *pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp) error
	converter00000 func(pkg_context.Context, *pkg_time.Time) (*pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp, error)
}

func (m *usermapper) ToProto(ctx pkg_context.Context, source *pkg_budgeting_system_internal_domain.User, dest *pkg_budgeting_system_internal_gen_budgy_v1.User) error {
	dest.Id = source.ID
	dest.Email = source.Email
	dest.FirstName = source.FirstName
	dest.LastName = source.LastName
	dest.BasiqUserId = source.BasiqUserID
	done5 := false
	if m.converter00000 != nil && !done5 {
		done5 = true
		if converted, err := m.converter00000(ctx, &(source.CreatedAt)); err != nil {
			return err
		} else {
			dest.CreatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done5 {
		done5 = true
		if dest.CreatedAt == nil {
			dest.CreatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.CreatedAt), dest.CreatedAt); err != nil {
			return err
		}
	}
	done6 := false
	if m.converter00000 != nil && !done6 {
		done6 = true
		if converted, err := m.converter00000(ctx, &(source.UpdatedAt)); err != nil {
			return err
		} else {
			dest.UpdatedAt = converted
		}
	}
	if m.mapper00000 != nil && !done6 {
		done6 = true
		if dest.UpdatedAt == nil {
			dest.UpdatedAt = new(pkg_google_golang_org_protobuf_types_known_timestamppb.Timestamp)
		}
		if err := m.mapper00000(ctx, &(source.UpdatedAt), dest.UpdatedAt); err != nil {
			return err
		}
	}
	if m.helper != nil {
		if err := m.helper.ToProto(ctx, source, dest); err != nil {
			return err
		}
	}
	return nil
}
