// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        string
	BudgetID  string
	Name      string
	Type      string
	Balance   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Budget struct {
	ID        string
	Name      string
	Method    string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Category struct {
	ID          string
	BudgetID    string
	Name        string
	Budgeted    int64
	Balance     int64
	TargetLimit int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type Transaction struct {
	ID          string
	BudgetID    string
	AccountID   string
	CategoryID  sql.NullString
	Amount      int64
	Description string
	Date        time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
