// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID             string
	BudgetID       sql.NullString
	Name           string
	Type           string
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Class          sql.NullString
	AccountNo      sql.NullString
	AvailableFunds sql.NullInt64
	Product        sql.NullString
	InstitutionID  sql.NullString
	ConnectionID   sql.NullString
	LastUpdated    sql.NullTime
}

type Budget struct {
	ID        string
	Name      string
	Method    string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    sql.NullString
}

type Category struct {
	ID          string
	BudgetID    sql.NullString
	Name        string
	Budgeted    int64
	Balance     int64
	TargetLimit int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type Transaction struct {
	ID             string
	BudgetID       sql.NullString
	AccountID      string
	CategoryID     sql.NullString
	Amount         int64
	Description    string
	Date           time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Direction      sql.NullString
	Status         sql.NullString
	Class          sql.NullString
	PostDate       sql.NullTime
	SubClass       sql.NullString
	RawDescription sql.NullString
	MerchantName   sql.NullString
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	BasiqUserID  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
