// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID             string
	UserID         string
	Name           string
	Type           string
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Class          sql.NullString
	AccountNo      sql.NullString
	AvailableFunds sql.NullInt64
	Product        sql.NullString
	InstitutionID  sql.NullString
	ConnectionID   sql.NullString
	LastUpdated    sql.NullTime
}

type BackgroundJob struct {
	ID           string
	JobType      string
	Payload      string
	Status       string
	Attempts     int32
	MaxAttempts  int32
	RunAt        time.Time
	ErrorMessage sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Budget struct {
	ID        string
	UserID    string
	Name      string
	Method    string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Period    string
	StartDate string
}

type BudgetAccount struct {
	BudgetID  string
	AccountID string
}

type BudgetCategoryLine struct {
	BudgetID          string
	CategoryID        string
	Budgeted          int64
	Balance           int64
	TargetLimit       int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BudgetedFrequency string
}

type Category struct {
	ID                string
	UserID            string
	ParentID          sql.NullString
	Name              string
	Type              string
	Color             string
	Icon              sql.NullString
	SortOrder         int32
	Archived          int32
	System            int32
	BasiqSubclassCode sql.NullString
	AnzsicClassCode   sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type EnvelopeAllocation struct {
	BudgetID   string
	AccountID  string
	CategoryID string
	Amount     int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type Transaction struct {
	ID              string
	AccountID       string
	CategoryID      sql.NullString
	Amount          int64
	Description     string
	Date            time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Direction       sql.NullString
	Status          sql.NullString
	Class           sql.NullString
	PostDate        sql.NullTime
	SubClass        sql.NullString
	RawDescription  sql.NullString
	MerchantName    sql.NullString
	MerchantWebsite sql.NullString
	MerchantLogoUrl sql.NullString
	LocationAddress sql.NullString
	LocationLat     sql.NullString
	LocationLng     sql.NullString
	CategoryCode    sql.NullString
	CategoryTitle   sql.NullString
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	BasiqUserID  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
